spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/edu_forms_test
    url: jdbc:postgresql://5.139.217.156:5432/edu_forms_test
    driver-class-name: org.postgresql.Driver
    username: user
    password: qwer1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        type: trace

jwt:
  header: Authorization
  secret: bigSecret
  expiration: 608400